runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: buy-and-sell-4f276:us-east1:buy-and-sell-gcloud
env_variables:
  DB_USER: hapi-server
  DB_PASS: abc123!abc123!
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-4f276:us-east1:buy-and-sell-gcloud
